name: Update README2

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: Readme-workflows/recent-activity@v2.4.1

      env:
        GITHIB_TOKEN: ${{ secrets.GITHUB+TOKEN }}
